In [2]:
import pickle
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, cross_validate

# baca dataset

In [3]:
data = pd.read_csv('https://raw.githubusercontent.com/DiahDSyntia/datamining-tugasakhir/main/indian_liver_patient.csv', sep=',')
data.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65       0              0.7               0.1                   187   
1   62       1             10.9               5.5                   699   
2   62       1              7.3               4.1                   490   
3   58       1              1.0               0.4                   182   
4   72       1              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

# Pemisahan Data

In [4]:
#ambil label setiap baris
label = data.iloc[:,-1:].values.ravel()
label

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2,
       2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1,
       2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2,

In [5]:
#ambil feature data
feature = data.iloc[:,:-1]
feature.values

array([[65.  ,  0.  ,  0.7 , ...,  6.8 ,  3.3 ,  0.9 ],
       [62.  ,  1.  , 10.9 , ...,  7.5 ,  3.2 ,  0.74],
       [62.  ,  1.  ,  7.3 , ...,  7.  ,  3.3 ,  0.89],
       ...,
       [52.  ,  1.  ,  0.8 , ...,  6.4 ,  3.2 ,  1.  ],
       [31.  ,  1.  ,  1.3 , ...,  6.8 ,  3.4 ,  1.  ],
       [38.  ,  1.  ,  1.  , ...,  7.3 ,  4.4 ,  1.5 ]])

In [6]:
#pembagian data latih dan uji sebanyak 80% dan latih 20% untuk data set
X_train, X_test, y_train, y_test = train_test_split(feature, label, test_size = 0.3)

In [7]:
print("Jumlah Data Latih:", len(X_train))
print("Jumlah Data Uji:", len(X_test))

Jumlah Data Latih: 405
Jumlah Data Uji: 174


# Pemodelan Dengan KNN

In [8]:
# Create KNN classifier
clf = KNeighborsClassifier(n_neighbors = 3)
# Fit the classifier to the data
clf.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

# Prediksi Hasil

In [9]:
pred = clf.predict(X_test)
pred

array([1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2,
       1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1])

In [ ]:
cols = {
    'Y True' : y_test,
    'Predict' : pred,
}

print("Prediksi yang dihasilkan")
pd.DataFrame(cols)

Prediksi yang dihasilkan


Y True  Predict
0         2        1
1         1        1
2         1        1
3         1        1
4         2        1
..      ...      ...
169       2        1
170       1        1
171       1        1
172       1        1
173       1        1

[174 rows x 2 columns]

# Pengukuran Permormance

In [ ]:
#fold = 10
kfold = KFold(n_splits=10)
scores = ['accuracy', 'precision', 'recall']
results = cross_validate(clf, X_test, y_test, cv=kfold, scoring=scores, return_train_score=True)
result_data = pd.DataFrame(results)
result_data

fit_time  score_time  test_accuracy  train_accuracy  test_precision  \
0  0.005657    0.007950       0.500000        0.814103        0.636364   
1  0.002385    0.004245       0.500000        0.807692        0.777778   
2  0.002365    0.004298       0.555556        0.807692        0.615385   
3  0.002379    0.004226       0.666667        0.801282        0.818182   
4  0.002525    0.004129       0.588235        0.821656        0.800000   
5  0.002334    0.004147       0.470588        0.802548        0.500000   
6  0.002358    0.004272       0.529412        0.802548        0.700000   
7  0.002279    0.004117       0.529412        0.808917        0.636364   
8  0.002351    0.004181       0.647059        0.808917        0.727273   
9  0.002387    0.005434       0.764706        0.815287        0.888889   

   train_precision  test_recall  train_recall  
0         0.895833     0.583333      0.819048  
1         0.876289     0.500000      0.825243  
2         0.880000     0.727273      0.830189  
3         0.876289     0.692308      0.817308  
4         0.887755     0.615385      0.836538  
5         0.881188     0.666667      0.824074  
6         0.870000     0.583333      0.828571  
7         0.880000     0.636364      0.830189  
8         0.865385     0.727273      0.849057  
9         0.873786     0.727273      0.849057

In [ ]:
print("PERFORMANCE MODEL KNN")

accuracy = result_data.test_accuracy.mean() * 100
precision = result_data.test_precision.mean() * 100
recall = result_data.test_recall.mean() * 100

print("Accuracy: %0.2f" % accuracy, "%")
print("Precision: %0.2f" % precision, "%")
print("Recall: %0.2f" % recall, "%")

PERFORMANCE MODEL KNN
Accuracy: 57.52 %
Precision: 71.00 %
Recall: 64.59 %


In [1]:
import pickle.dump(clf, open('liverflask', 'wb'))

SyntaxError: ignored